Server:
  port: 5005
  runMode: debug
logger:
  filePath: ../logs/logs.log
  encoding: json
  level: debug
cors:
  allowedOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  dbname: car_app
  sslMode: disable
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 60
Password:
  IncludeChars: true
  IncludeDigits: true
  IncludeUppers: true
  IncludeLowers: true
  minLength: 8
  maxLength: 16