Server:
  port: 5005
  runMode: debug
logger:
  filePath: logs/logs.log
  encoding: json
  level: debug
  type: zap
cors:
  allowedOrigins: "*"
postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: password
  dbname: car_sale
  sslMode: disable
  maxIdleConnections: 15
  maxOpenConnections: 100
  maxLifetime: 5
redis:
  host: 127.0.0.1
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 60
Password:
  IncludeChars: true
  IncludeDigits: true
  IncludeUppers: true
  IncludeLowers: true
  minLength: 8
  maxLength: 16