server:
  port: 5005
  runMode: debug
logger:
  filePath: logs/logs.log
  encoding: json
  level: debug
  type: zap
cors:
  allowedOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: car_sale
  sslMode: disable
  maxIdleConnections: 15
  maxOpenConnections: 100
  maxLifetime: 5
redis:
  host: localhost
  port: 6379
  password:
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 60
password:
  IncludeChars: true
  IncludeDigits: true
  IncludeUppers: true
  IncludeLowers: true
  minLength: 8
  maxLength: 16
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 60

